# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/createWithArray_post for http method type POST 
# RoostTestHash=2fceff8367
# 
# 

# ********RoostGPT********
Feature: User creation with array input

Background:
    * url target
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': 'Bearer ' + authToken }

Scenario: Creating list of users with given input array

    Given path '/v2/user/createWithArray'
    And request [{id: 1, username: 'testuser1', firstName: 'Test', lastName: 'User', email: 'testuser1@example.com', password: 'password', phone: '1234567890', userStatus: 1}, {id: 2, username: 'testuser2', firstName: 'Test', lastName: 'User', email: 'testuser2@example.com', password: 'password', phone: '0987654321', userStatus: 2}]
    When method post
    Then status 200
    And match response == {description: 'successful operation'}
