# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/createWithList_post for http method type POST 
# RoostTestHash=41ad79e90d
# 
# 

# ********RoostGPT********
Feature: User creation with list

Background:
  * def API_HOST = karate.properties['API_HOST']
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * url API_HOST

Scenario: Create users with list
  Given path '/v2/user/createWithList'
  And request { id: '#(id)', username: '#(username)', firstName: '#(firstName)', lastName: '#(lastName)', email: '#(email)', password: '#(password)', phone: '#(phone)', userStatus: '#(userStatus)' }
  And header Authorization = AUTH_TOKEN
  When method post
  Then status 200
  And match response == { description: 'successful operation' }

Examples:
| id | username | firstName | lastName | email        | password | phone      | userStatus |
| 1  | 'user1'  | 'John'    | 'Doe'    | 'jd@test.com'| 'pass1'  | '123456789'| 1          |
| 2  | 'user2'  | 'Jane'    | 'Doe'    | 'jdoe@test.com'| 'pass2'| '987654321'| 0          |
