# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/login_get for http method type GET 
# RoostTestHash=d905dac95c
# 
# 

# ********RoostGPT********
Feature: User Login

Background: 
  * url target
  * def authToken = karate.env == 'stage' ? karate.properties['stage.authToken'] : karate.properties['prod.authToken']

Scenario: Successful User Login
  Given path '/v2/user/login'
  And params { username: '#(username)', password: '#(password)' }
  When method get
  Then status 200
  And match responseHeaders contains { 'X-Expires-After': '#string', 'X-Rate-Limit': '#number' }
  And match response == '#string'

Scenario: Failed User Login - Invalid Credentials
  Given path '/v2/user/login'
  And params { username: 'invaliduser', password: 'invalidpass' }
  When method get
  Then status 400

Examples:
  | username  | password  |
  | 'testuser' | 'testpass' |
