# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order/{orderId}_delete for http method type DELETE 
# RoostTestHash=36caaf0283
# 
# 

# ********RoostGPT********
Feature: Order Management

  Background:
    * url target
    * header Authorization = 'Bearer ' + $processEnvironment.AUTH_TOKEN

  Scenario: Delete purchase order by ID
    Given path '/v2/store/order/', orderId
    And method delete
    When request
    Then status 200
    And match response == { success: '#boolean' }

    Examples:
      | orderId |
      | 1       |
      | 2       |
      | 3       |
