# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1138243cb1
# 
# 

# ********RoostGPT********
Feature: Petstore API

  Background:
    * url target
    * def authToken = $processEnvironment.AUTH_TOKEN
    * configure headers = { 'api_key': '#(authToken)' }

  Scenario: Delete a pet
    Given path '/v2/pet/', petId
    And header api_key = authToken
    When method delete
    Then status 200
    And match response == { "message": 'Pet deleted successfully' }

    Examples:
      | petId |
      | 1     |
      | 2     |
      | 3     |

  Scenario: Try to delete a pet with invalid ID
    Given path '/v2/pet/', petId
    And header api_key = authToken
    When method delete
    Then status 400
    And match response == { "message": 'Invalid ID supplied' }

    Examples:
      | petId |
      | 'invalid' |
      | -1        |
      | 0         |

  Scenario: Try to delete a pet not found
    Given path '/v2/pet/', petId
    And header api_key = authToken
    When method delete
    Then status 404
    And match response == { "message": 'Pet not found' }

    Examples:
      | petId |
      | 99999 |
      | 88888 |
      | 77777 |
