# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet_put for http method type PUT 
# RoostTestHash=ec103be570
# 
# 

# ********RoostGPT********
Feature: Pet Store API

Background:
    * url target
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

Scenario: Update an existing pet
    Given path '/v2/pet'
    And request
    """
    {
        "id": 1,
        "category": {
            "id": 1,
            "name": "Dogs"
        },
        "name": "doggie",
        "photoUrls": ["string"],
        "tags": [
            {
                "id": 1,
                "name": "tag1"
            }
        ],
        "status": "available"
    }
    """
    When method put
    Then status 200
    And match response ==
    """
    {
        "id": '#number',
        "category": {
            "id": '#number',
            "name": '#string'
        },
        "name": '#string',
        "photoUrls": ['#string'],
        "tags": [
            {
                "id": '#number',
                "name": '#string'
            }
        ],
        "status": '#string'
    }
    """

Scenario Outline: Negative Test - Update an existing pet with invalid data
    Given path '/v2/pet'
    And request
    """
    {
        "id": "<id>",
        "category": {
            "id": "<categoryId>",
            "name": "<categoryName>"
        },
        "name": "<name>",
        "photoUrls": ["<photoUrl>"],
        "tags": [
            {
                "id": "<tagId>",
                "name": "<tagName>"
            }
        ],
        "status": "<status>"
    }
    """
    When method put
    Then status <statusCode>

    Examples:
    | id  | categoryId | categoryName | name  | photoUrl | tagId | tagName | status     | statusCode |
    | 'a' | 1          | 'Dogs'       | 'Dog' | 'string' | 1     | 'tag1'  | 'available'| 400        |
    | 1   | 'a'        | 'Dogs'       | 'Dog' | 'string' | 1     | 'tag1'  | 'available'| 400        |
    | 1   | 1          | 'Dogs'       | 'Dog' | 'string' | 'a'   | 'tag1'  | 'available'| 400        |
    | 1   | 1          | 'Dogs'       | 'Dog' | 'string' | 1     | 'tag1'  | 'invalid'  | 400        |
