# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=c0bc5294a0
# 
# 

# ********RoostGPT********
Feature: Pet Store API

Background:
    * def API_HOST = karate.env == 'dev' ? 'dev.api.com' : 'prod.api.com'
    * def AUTH_TOKEN = karate.env == 'dev' ? 'dev_token' : 'prod_token'
    * url API_HOST
    * header Authorization = AUTH_TOKEN

Scenario: Updates a pet in the store with form data

Given path '/v2/pet/{petId}'
And params { petId: '#(petId)' }
And form field name = '#(name)'
And form field status = '#(status)'
When method post
Then status 200
And match response == { petId: '#(petId)', name: '#(name)', status: '#(status)' }

Examples:
| petId | name     | status    |
| 1      | 'Rex'    | 'Sold'    |
| 2      | 'Bella'  | 'Available'|
| 3      | 'Max'    | 'Pending' |
