# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=018c365850
# 
# 

# ********RoostGPT********
Feature: Pet Store API Tests

Background:
* url target
* def auth = { Authorization: '#(authToken)' }

@PetStore
Scenario: Test GET /v2/pet/{petId} endpoint with valid petId
  * def petId = 1
  Given path 'v2/pet', petId
  And headers auth
  When method get
  Then status 200
  And match response == { id: '#(petId)', name: '#string', photoUrls: '#[]', status: '#string' }

@PetStore
Scenario: Test GET /v2/pet/{petId} endpoint with invalid petId
  * def petId = 'invalid'
  Given path 'v2/pet', petId
  And headers auth
  When method get
  Then status 400

@PetStore
Scenario: Test GET /v2/pet/{petId} endpoint with petId not found
  * def petId = 999999
  Given path 'v2/pet', petId
  And headers auth
  When method get
  Then status 404
