# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pets/{petId}_get for http method type GET 
# RoostTestHash=a2ba717256
# 
# 

# ********RoostGPT********
Feature: Pets API

Background:
    * url target
    * header Authorization = 'Bearer ' + $processEnvironment.AUTH_TOKEN

Scenario: Get pet by ID

    Given path 'pets', '1'
    When method get
    Then status 200
    And match response contains {id:'#number', name:'#string', tag:'#string'}

Scenario: Get pet by ID - pet not found

    Given path 'pets', '9999'
    When method get
    Then status 404
    And match response contains {code:'#number', message:'#string'}

Examples:
| petId |
| '1'   |
| '9999'|
