# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pets/{id}_get for http method type GET 
# RoostTestHash=8382372fdc
# 
# 

# ********RoostGPT********
Feature: Pet Store API

Background:
* url target
* def authToken = $processEnvironment.AUTH_TOKEN
* def headers = { Authorization: '#(authToken)' }

Scenario: Find pet by ID
Given path 'pets', 1
And headers headers
When method get
Then status 200
And match response contains { name: '#string', tag: '#string', id: '#number' }

Scenario Outline: Find pet by ID with different inputs
Given path 'pets', <id>
And headers headers
When method get
Then status <status>
And match response contains { name: '#string', tag: '#string', id: '#number' }

Examples:
| id | status |
| 1  | 200    |
| 2  | 200    |
| 3  | 404    |

Scenario: Find pet by ID and unexpected error
Given path 'pets', 9999
And headers headers
When method get
Then status 500
And match response contains { code: '#number', message: '#string' }
