# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pets_get for http method type GET 
# RoostTestHash=13f57c0784
# 
# 

# ********RoostGPT********
Feature: List all pets

Background:
* url target
* def authToken = karate.properties['AUTH_TOKEN']

Scenario: Test GET /pets with limit parameter

Given path '/pets'
And param limit = 10
And header Authorization = authToken
When method GET
Then status 200
And match each response contains { id: '#number', name: '#string', tag: '#?string' }
And match header contains { 'x-next': '#?string' }

Scenario: Test GET /pets without limit parameter

Given path '/pets'
And header Authorization = authToken
When method GET
Then status 200
And match each response contains { id: '#number', name: '#string', tag: '#?string' }
And match header contains { 'x-next': '#?string' }

Scenario Outline: Test GET /pets with negative limit parameter

Given path '/pets'
And param limit = <limit>
And header Authorization = authToken
When method GET
Then status 400

Examples:
| limit |
| -1    |
| -10   |
| -100  |

Scenario: Test GET /pets with limit parameter exceeding maximum

Given path '/pets'
And param limit = 101
And header Authorization = authToken
When method GET
Then status 400

Scenario: Test GET /pets with non-integer limit parameter

Given path '/pets'
And param limit = 'abc'
And header Authorization = authToken
When method GET
Then status 400
