# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pets/{id}_delete for http method type DELETE 
# RoostTestHash=425309a929
# 
# 

# ********RoostGPT********
Feature: Pet Store API

  Background:
    * url target
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

  Scenario: Delete a pet by ID
    Given path 'pets', 1
    When method delete
    Then status 204

  Scenario: Delete a pet by ID and verify response
    Given path 'pets', 1
    When method delete
    Then status 204
    And match response == { }

  Scenario: Verify error response when deleting a non-existent pet
    Given path 'pets', 9999
    When method delete
    Then status 404
    And match response contains { code: '#number', message: '#string' }
