# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pets_post for http method type POST 
# RoostTestHash=2973e293f4
# 
# 

# ********RoostGPT********
Feature: Pet Store API Tests

Background:
  * def API_HOST = karate.env == 'dev' ? 'dev.api.com' : 'prod.api.com'
  * def AUTH_TOKEN = karate.env == 'dev' ? 'dev_token' : 'prod_token'
  * url API_HOST
  * header Authorization = AUTH_TOKEN

Scenario: Test Add Pet API
  Given path '/pets'
  And request {"name": "#(name)", "tag": "#(tag)"}
  When method post
  Then status 200
  And match response contains {"name": "#(name)", "tag": "#(tag)"}

Examples:
  | name  | tag   |
  | 'Tom' | 'cat' |
  | 'Max' | 'dog' |
