# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pets/{petId}_get for http method type GET 
# RoostTestHash=a2ba717256
# 
# 

# ********RoostGPT********
Feature: Pets API

Background:
  * url target
  * header Authorization = 'Bearer ' + auth_token

Scenario Outline: Get info for a specific pet

  Given path '/pets/', <petId>
  When method get
  Then status 200
  And match response contains {id:'#number', name:'#string', tag:'#?string'}

  Examples:
    | petId |
    | '1'   |
    | '2'   |
    | '3'   |

Scenario Outline: Handle unexpected error

  Given path '/pets/', <petId>
  When method get
  Then status != 200
  And match response contains {code:'#number', message:'#string'}

  Examples:
    | petId  |
    | 'abc'  |
    | '1234' |
    | 'xyz'  |
