# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /products/{productId}_delete for http method type DELETE 
# RoostTestHash=befb82c928
# 
# 

# ********RoostGPT********
Feature: Delete Product API

  Background:
    * url target = karate.properties['API_HOST']
    * def auth = karate.properties['AUTH_TOKEN']
    * def payload = read('products_productId_delete_karate.csv')

  Scenario: Verify valid delete product API behavior with valid input payload

    Given path '/products/', payload.productId
    And header Authorization = auth

    # Delete a product
    When method delete
    Then status 200
    And match response == { description: 'Product deleted' }

    # Verify the product is deleted
    Given path '/products/', payload.productId
    And header Authorization = auth
    When method get
    Then status 404
    And match response == { description: 'Not Found' }
