# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /products/{productId}_delete for http method type DELETE 
# RoostTestHash=befb82c928
# 
# 

# ********RoostGPT********
Feature: Delete Product API

  Background:
    * url target = karate.env == 'dev' ? 'http://dev.api.com' : 'http://prod.api.com'
    * def authToken = karate.properties['AUTH_TOKEN']
    * def deleteProductPayload = read('classpath:products_productId_delete_karate.csv')

  Scenario: Delete a product with valid product id
    Given path '/products/{productId}'
    And header Authorization = authToken
    And request deleteProductPayload
    When method delete
    Then status 200
    And match response == { description: 'Product deleted' }

  Scenario: Delete a product with invalid product id
    Given path '/products/{invalidProductId}'
    And header Authorization = authToken
    And request deleteProductPayload
    When method delete
    Then status 404
    And match response == { description: 'Not Found' }
