# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=ab8efa24ed
# 
# 

# ********RoostGPT********
Feature: Testing /products/{productId} endpoint

Background:
  * url target = 'http://localhost:8080'
  * def authToken = karate.properties['AUTH_TOKEN']
  * def productId = read('products_productId_get.csv')

Scenario: Find product by ID
  Given path '/products/', productId.productId
  And header Authorization = authToken
  When method get
  Then status 200
  And match response == { id: '#(productId.productId)', name: '#string', description: '#string', price: '#number' }

Scenario: Product not found 
  Given path '/products/', 'nonExistentId'
  And header Authorization = authToken
  When method get
  Then status 404
