# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /products/{productId}_put for http method type PUT 
# RoostTestHash=7b2a6b6959
# 
# 

# ********RoostGPT********
Feature: Update a product in the store

  Background:
    * url target
    * header Authorization = $processEnvironment.AUTH_TOKEN
    * def productId = __arg
    * def payload = read('products_productId_put.csv')
  
  Scenario: Update a product with valid data
    Given path 'products', productId
    And request payload
    When method put
    Then status 200
    And match response == {id:'#(productId)', name:'#(payload.name)', description:'#(payload.description)', price:'#(payload.price)'}
  
  Scenario: Update a non-existent product
    Given path 'products', 9999
    And request payload
    When method put
    Then status 404
