# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /products/{productId}_delete for http method type DELETE 
# RoostTestHash=befb82c928
# 
# 

# ********RoostGPT********
Feature: Delete Product API

  Background:
    * url target = karate.env == 'dev' ? 'http://dev.api.com' : 'http://prod.api.com'
    * header Authorization = karate.properties['AUTH_TOKEN']
    * def payload = read('classpath:products_productId_delete_karate.csv')
    * configure headers = { 'Content-Type': 'application/json' }

  Scenario: Delete a product
    Given path '/products/{productId}'
    And request payload
    When method delete
    Then status 200
    And match response contains { 'description': 'Product deleted' }

  Scenario: Delete a product with non-existing productId
    Given path '/products/{productId}'
    And request payload
    When method delete
    Then status 404
    And match response contains { 'description': 'Not Found' }
