# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roost-gpt4-32k
# 
# Test generated for /products/{productId}_put for http method type PUT in karate framework
# RoostTestHash=7b2a6b6959
# 
# 

# ********RoostGPT********
Feature: Validate product update API

  Background:
    * url target = karate.env == 'local' ? 'http://localhost:8080' : 'https://${API_HOST}'
    * configure headers = { Authorization: '#(authToken)' }
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure csv = { payload: 'products_productId_put_karate.csv', skipHeaders: true }

  Scenario Outline: Update product details and validate response

    # Updating Product details
    Given path '/product/', productId
    And request { id: '#(id)', name: '#(name)', description: '#(description)', price: '#(price)' }
    When method put
    Then status 200

    # Asserting response headers
    And match header contains { Server: '#string', 'Content-Length': '#string', 'Set-Cookie': '#string' }

    # Asserting response body
    And match response == { id: '#(id)', name: '#(name)', description: '#(description)', price: '#(price)' }

    Examples:
      | payload |

