# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=ab8efa24ed
# 
# 

# ********RoostGPT********
Feature: Find product by ID

Background:
  * url target
  * header Authorization = $processEnvironment.AUTH_TOKEN
  * def productId = read('payload/products_productId_get_.csv')

Scenario: Verify successful retrieval of product by ID

  Given path 'products', productId.someProductId.value
  When method get
  Then status 200
  And match response == {id:'#(productId.someProductId.value)', name:'#string', description:'#string', price:'#number'}
  And match responseHeaders contains { 'Content-Type': 'application/json' }

Scenario: Verify retrieval of non-existent product ID fails

  Given path 'products', 999999999
  When method get
  Then status 404
