# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_delete for http method type DELETE 
# RoostTestHash=5caa5e3efb
# 
# 

# ********RoostGPT********
Feature: User Management

Background:
  * url target
  * def auth = $processEnvironment.AUTH_TOKEN
  * header Authorization = auth

Scenario: Delete user - valid username
  Given path 'v2', 'user', '<username>'
  And method delete
  When method delete
  Then status 200

  Examples:
    | username |
    | 'John'   |
    | 'Doe'    |

Scenario: Delete user - invalid username
  Given path 'v2', 'user', '<username>'
  And method delete
  When method delete
  Then status 400

  Examples:
    | username |
    | ''       |
    | '123'    |

Scenario: Delete user - user not found
  Given path 'v2', 'user', '<username>'
  And method delete
  When method delete
  Then status 404

  Examples:
    | username |
    | 'NonExistentUser' |
