# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_get for http method type GET 
# RoostTestHash=b96457affd
# 
# 

# ********RoostGPT********
Feature: Testing /v2/user/{username} endpoint

Background: 
  * url '{{$processEnvironment.API_HOST}}'
  * def auth = '{{$processEnvironment.AUTH_TOKEN}}'

  Scenario: Get user by username
    Given path '/v2/user/', 'user1'
    And header Authorization = auth
    When method get
    Then status 200
    And match response == {id:'#number', username:'#string', firstName:'#string', lastName:'#string', email:'#string', password:'#string', phone:'#string', userStatus:'#number'}

  Scenario Outline: Get user by username with invalid inputs
    Given path '/v2/user/', <username>
    And header Authorization = auth
    When method get
    Then status <status_code>

    Examples: 
      | username | status_code |
      | ''       | 400         |
      | 'abc'    | 404         |
      | null     | 400         |
