# ********RoostGPT********

# Test generated by RoostGPT for test MultipleApiSpec using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /apikeys_post for http method type POST 
# RoostTestHash=7212880a1c
# 
# 

# ********RoostGPT********
Feature: Testing the /apikeys endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['authToken'] || karate.get('authToken', '{{$processEnvironment.AUTH_TOKEN}}')
  * configure headers = { Token: '#(authToken)' }

Scenario: Test successful API Key creation
  Given path '/apikeys'
  When method post
  Then status 201
  And match header api-version == '1.0.0'
  And match header location contains '/apikeys'
  And match response contains { id: '#string', token: '#regex[^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$]', createdAt: '#string' }

Scenario: Test API Key creation with bad request
  Given path '/apikeys'
  And request { invalid: 'payload' }
  When method post
  Then status 400
  And match header api-version == '1.0.0'
  And match response contains { error: '#string', description: '#string' }

Scenario: Test API Key creation without authentication
  Given path '/apikeys'
  And configure headers = { Token: 'invalidToken' }
  When method post
  Then status 401
  And match header api-version == '1.0.0'
  And match response contains { error: '#string', description: '#string' }
