# ********RoostGPT********

# Test generated by RoostGPT for test MultipleApiSpec using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /apikeys_get for http method type GET 
# RoostTestHash=9cb45f5182
# 
# 

# ********RoostGPT********
Feature: API keys

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'dummyToken')
  * def authHeaders = { 'Token': '#(authToken)' }

Scenario: List API Keys you have created (session.type = 4)
  Given path '/apikeys'
  And headers authHeaders
  When method get
  Then status 200
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { total:'#number', apikeys:'#[] apikeys' }
  And match each response.apikeys == { id:'#uuid', createdAt:'#string' }

Scenario: Invalid request to list API Keys
  Given path '/apikeys'
  And headers authHeaders
  When method get
  Then status 400
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { error:'#string', description:'#string' }

Scenario: Authentication required to list API Keys
  Given path '/apikeys'
  And headers { 'Token': 'invalidToken' }
  When method get
  Then status 401
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { error:'#string', description:'#string' }
