# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=8dac89cb33
# 
# 

# ********RoostGPT********
Feature: uploads an image

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken')
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Test upload image with valid inputs
  Given path '/v2/pet/{petId}/uploadImage'
  And param petId = '#(petId)'
  And multipart field additionalMetadata = '#(additionalMetadata)'
  And multipart file file = { read: '#(filePath)', filename: '#(fileName)', contentType: 'multipart/form-data' }
  When method post
  Then status 200
  And match response == { code: '#(code)', type: '#(type)', message: '#(message)' }

Examples:
  | petId | additionalMetadata | filePath                | fileName | code | type | message |
  | 123   | 'Test metadata'   | 'src/test/resources/image.jpg' | 'image.jpg' | 200  | 'string' | 'successful operation' |
