# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=467fc95f1c
# 
# 

# ********RoostGPT********
Feature: Testing /v2/pet/findByStatus endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'my_default_auth_token')
  * configure headers = {Authorization: '#(authToken)'}

Scenario Outline: Find Pets by status
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 200
  And match response contains {name:'#string', photoUrls:'#[]'}
  And match response[*].id == '#number'
  And match response[*].category == {id:'#number', name:'#string'}
  And match response[*].status == '#string'

  Examples:
    | status       |
    | 'available'  |
    | 'sold'       |
    | 'pending'    |
