# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=467fc95f1c
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/findByStatus endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['auth.token'] || karate.get('authToken', 'default_token')
  * configure headers = { Authorization: '#(auth_token)' }

Scenario Outline: Test GET method with valid status
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 200
  And match each response contains { 'name': '#string', 'photoUrls': '#[]' }
  And match each response contains { 'status': '#(status)' }

  Examples:
    | status    |
    | 'available' |
    | 'pending'  |
    | 'sold'     |

Scenario Outline: Test GET method with invalid status
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 400

  Examples:
    | status    |
    | 'invalid' |
    | 'unknown' |
