# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=8dac89cb33
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/{petId}/uploadImage API endpoint

Background:
  * def AuthToken = karate.properties['AUTH_TOKEN']
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Validate the Upload Image API endpoint using a valid petId and image file
  Given path '/v2/pet', '<petId>', 'uploadImage'
  And header Authorization = AuthToken
  And multipart field file = { read: 'file_to_upload.jpeg', filename: 'file_to_upload.jpeg', contentType: 'multipart/form-data' }
  And multipart field additionalMetadata = '<metadata>'
  When method post
  Then status 200
  And match response == { code: '#(200)', type: '##string', message: '##string' }

  Examples:
    | petId | metadata             |
    | 12345 | 'Test metadata'      |
    | 67890 | 'Another test entry' |
