# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=467fc95f1c
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/findByStatus endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'defaultToken')
  * configure headers = {Authorization: '#(authToken)'}

Scenario: Test GET request with valid status
  Given path '/v2/pet/findByStatus'
  And param status = 'available'
  When method get
  Then status 200
  And match response contains {name: '#string', photoUrls: '#[]'}
  And match response[*].status == 'available'

Scenario: Test GET request with invalid status
  Given path '/v2/pet/findByStatus'
  And param status = 'invalid'
  When method get
  Then status 400

Examples:
  | status     |
  | 'available'|
  | 'pending'  |
  | 'sold'     |
