# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet_post for http method type POST 
# RoostTestHash=33f954929c
# 
# 

# ********RoostGPT********
Feature: API Endpoint for '/v2/pet'

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['AUTH_TOKEN']
  * configure headers = {Authorization: '#(auth_token)'}

Scenario: Add a new pet to the store

  Given path '/v2/pet'
  And request { id: #(id), name: #(name), category: { id: #(categoryId), name: #(categoryName) }, photoUrls: '#(photoUrls)', tags: [{ id: #(tagId), name: #(tagName) }], status: #(status) }
  When method post
  Then status 200
  And match response == { id: '#(id)', name: '#(name)', category: { id:
   '#(categoryId)', name: '#(categoryName)' }, photoUrls: '#(photoUrls)', tags: [{ id: '#(tagId)', name: '#(tagName) }], status: '#(status)' }

  Examples:
    | id  | name   | categoryId | categoryName | photoUrls             | tagId | tagName | status   |
    | 101 | 'dog'  | 1          | 'animal'     | ['url1', 'url2']      | 11    | 'tag1'  | 'sold'   |
    | 102 | 'cat'  | 2          | 'animal'     | ['url3', 'url4']      | 12    | 'tag2'  | 'pending'|
    | 103 | 'fish' | 3          | 'animal'     | ['url5', 'url6']      | 13    | 'tag3'  | 'available' |

Scenario: When Adding a new pet to store with invalid input

  Given path '/v2/pet'
  And request { id: #(idInvalid), name: #(nameInvalid), category: { id: #(categoryIdInvalid), name: '#(categoryNameInvalid)' }, photoUrls: '#(photoUrlsInvalid)', tags: [{ id: #'(tagIdInvalid)', name: '#(tagNameInvalid)' }], status: '#(statusInvalid)' }
  When method post
  Then status 405
  And match response.description == 'Invalid input'

  Examples:
    | idInvalid | nameInvalid | categoryIdInvalid | categoryNameInvalid | photoUrlsInvalid    | tagIdInvalid | tagNameInvalid | statusInvalid |
    | 104       | 'bird'      | 4                 | ' '                 | [' ']              | 14           | ' '            | 'unknown'     |
