# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1138243cb1
# 
# 

# ********RoostGPT********
Feature: API test for /v2/pet/{petId} to delete a pet

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Validates that pet can be deleted using the provided petId and response codes are appropriate

    Given path 'v2/pet', <petId>
    And header Authorization = authToken
    And header api_key = karate.properties['api_key']

    When method DELETE

    Then match responseStatus == <responseCode>
    And match responseHeaders contains { 'Content-Type': 'application/json'}

    Examples:
    | petId | responseCode |
    | 100   | 200          |
    | 101   | 404          |
    | 102   | 400          |
