# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=01adc2ed1e
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/findByTags endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken', 'defaultToken')
  * configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Find pets by tags
  Given path '/v2/pet/findByTags'
  And param tags = <tags>
  When method get
  Then status 200
  And match response is { type: '#array', items: '#object' }
  And match each response contains { name: '#string', photoUrls: '#array' }
  And match each response.name == 'doggie'
  And match each response.status == '#string'

  Examples:
    | tags               |
    | ['tag1', 'tag2']   |
    | ['tag3', 'tag4']   |
    | ['tag5', 'tag6']   |

Scenario: Invalid tag value
  Given path '/v2/pet/findByTags'
  And param tags = ['invalidTag']
  When method get
  Then status 400

