# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1138243cb1
# 
# 

# ********RoostGPT********
Feature: Deletes a pet

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.get('authToken', '{{ $processEnvironment.AUTH_TOKEN }}')
  * configure headers = { 'api_key': '#(authToken)' }

Scenario: Delete a pet with valid petId
  Given path 'v2', 'pet', 1
  When method delete
  Then status 200
  And match response == { }

Scenario: Delete a pet with invalid petId
  Given path 'v2', 'pet', 'invalid'
  When method delete
  Then status 400
  And match response == { }

Scenario: Delete a pet with non-existent petId
  Given path 'v2', 'pet', 9999
  When method delete
  Then status 404
  And match response == { }

Scenario Outline: Delete a pet with different petIds
  Given path 'v2', 'pet', <petId>
  When method delete
  Then status <statusCode>

  Examples:
    | petId | statusCode |
    | 1     | 200        |
    | 'invalid' | 400    |
    | 9999   | 404       |
