# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=9124f669d9
# 
# 

# ********RoostGPT********
Feature: Testing Pet Endpoints features 

Background: 
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * header Authorization = authToken

Scenario: Verify the successful operation of getting pet details by tags
  Given path '/v2/pet/findByTags'
  And param tags = ['pet']
  When method get
  Then status 200
  And match response contains {id: '#number', category: '#object', name: '##string', photoUrls: '#[]', tags: '#[]', status: '#string' }

Scenario: Verify the operation of getting pet details by tags with invalid tag
  Given path '/v2/pet/findByTags'
  And param tags = ['InvalidTag']
  When method get
  Then status 400

Examples:
  |tags        |
  |'pet1'      |
  |'pet2'      |
  |'InvalidTag'|                  
