# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=9124f669d9
# 
# 

# ********RoostGPT********
Feature: Finds Pets by tags

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* def auth_token = karate.properties['AUTH_TOKEN']
* header api_key = auth_token

Scenario Outline: Get pets by tags via query parameters
  Given path '/v2/pet/findByTags'
  And param tags = '<tags>'
  When method get
  Then status 200
  And match response is {type: '#array'}
  And match each response[*] == {"id":"#number", "category": {"id":"#number", "name":"#string"}, "name": "#string", "photoUrls": '#array', "tags":'#array', "status":"#string"}
  And match response[*].status contains only ['available','pending','sold']

Examples:
| tags               |
| 'cat,dog,parrot'   |
| 'snake,hamster'    |
| 'elephant,giraffe' |

Scenario: Get pets by tags via query parameters with invalid tag value
  Given path '/v2/pet/findByTags'
  And param tags = 'invalid_tag'
  When method get
  Then status 400
