# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=44cafec54d
# 
# 

# ********RoostGPT********
Feature: Petstore Pet API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080') 
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = { 'api_key': '#(AUTH_TOKEN)' }

Scenario Outline: Finds Pets by status
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 200
  And match each response contains { 'name': '#string', 'photoUrls' : '#[] #string', 'status' : '<status>', 'id':'#integer', 'tags' : '#[]'}
  And assert response.length > 0

  Examples:
    | status    |
    | 'available' |
    | 'pending'   |
    | 'sold'      |
