# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=44cafec54d
# 
# 

# ********RoostGPT********
 Feature: Testing /v2/pet/findByStatus API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = { api_key: '#(AUTH_TOKEN)' }

Scenario Outline: Verify that pets can be searched by status
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 200
  And match each response contains {name:'#string', photoUrls:'#[]'}
  And match each response.status == '<status>'
  Examples:
      | status     |
      | 'available'|
      | 'pending'  |
      | 'sold'     |

Scenario Outline: Verify error handling for invalid status value
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status 400
  And match response.error == 'Invalid status value'
  Examples:
      | status   |
      | 'invalid'|
