# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=9124f669d9
# 
# 

# ********RoostGPT********
Feature: Testing /v2/pet/findByTags API endpoint

Background: 
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* def authToken = karate.properties['AUTH_TOKEN'] || karate.get('authToken')
* configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Find Pets by tags

Given path '/v2/pet/findByTags'
And param tags = '<tags>'
When method get
Then status 200
And match response contains {"name":"#string", "photoUrls":"#[]"}
And assert response.schema.items.required.contains('name')
And assert response.schema.items.required.contains('photoUrls')

Examples:
| tags              |
| 'tag1,tag2,tag3'  |
| 'cat,dog,rabbit'  |

Scenario Outline: Find Pets by tags - invalid tag value

Given path '/v2/pet/findByTags'
And param tags = '<invalidTags>'
When method get
Then status 400

Examples:
| invalidTags |
| ''          |
| '  '        |
