# ********RoostGPT********

# Test generated by RoostGPT for test products-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=44cafec54d
# 
# 

# ********RoostGPT********
Feature: Finds Pets by status

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * configure headers = {api_key: '#(karate.properties['AUTH_TOKEN'])'}

Scenario Outline: validate get request
  Given path '/v2/pet/findByStatus'
  And param status = '<status>'
  When method get
  Then status <status_code>
  And match each response == {name:'#string', photoUrls:'#array'}
  
  Examples:
    | status    | status_code |
    | 'pending' | 200         |
    | 'sold'    | 200         |
    | 'available'| 200        |
    | 'invalid' | 400         |
